package com.miniplm.entity;

public enum PrivilegeEnum {
	CREATE, READ, MODIFY, CREATE_TABLE, MODIFY_TABLE, UPLOAD_SELF_FILE, DELETE_SELF_FILE, UPLOAD_OTHERS_FILE, DELETE_OTHERS_FILE, GET_FILE, CHANGE_STEP, ADD_APPROVER, REMOVE_APPROVER
}
