package com.miniplm.entity;

public enum PrivilegeEnum {
	CREATE, READ, MODIFY, UPLOAD_SELF_FILE, DELETE_SELF_FILE, UPLOAD_OTHERS_FILE, DELETE_OTHERS_FILE, GET_FILE, START_WORKFLOW, CHANGE_STEP, APPROVE_REJECT
}
